"""initial schema

Revision ID: 31a152d7c4d8
Revises: 
Create Date: 2026-08-14 18:03:23.189723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a152d7c4d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=False),
    sa.Column('mood_base', sa.String(length=32), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('mood_drift', sa.Float(), nullable=False),
    sa.Column('memory_summaries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    comment='Raw scraped news; purged per retention policy'
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source'), 'news_articles', ['source'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Enum('asubuhi', 'mchana', 'usiku', name='timeofday'), nullable=False),
    sa.Column('full_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('characters_delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_created_at'), 'scripts', ['created_at'], unique=False)
    op.create_table('memory_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.String(length=64), nullable=False),
    sa.Column('script_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_events_character_id'), 'memory_events', ['character_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_client_id'), 'votes', ['client_id'], unique=False)
    op.create_index(op.f('ix_votes_script_id'), 'votes', ['script_id'], unique=False)
    # ### end Alembic commands ###

    # Record the schema version so check_schema_version() (engine.py) passes.
    op.execute("INSERT INTO app_meta (key, value) VALUES ('schema_version', '1')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM app_meta WHERE key = 'schema_version'")
    op.drop_index(op.f('ix_votes_script_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_client_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_memory_events_character_id'), table_name='memory_events')
    op.drop_table('memory_events')
    op.drop_index(op.f('ix_scripts_created_at'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_news_articles_source'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('characters')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
